try:
    result=45/5
except:
    print('error happend')
finally:
    print('i am here')
print('done')